;;;; vt100.lisp

(in-package #:vt100)

;;; "vt100" goes here. Hacks and glory await!

;;; See http://www.termsys.demon.co.uk/vtansi.htm for reference

;; character codes are stringified, <ESC> replaced with #\Space
;;  {variable} replaced with ~A with variable as an argument
;;  Names are lispified versions of the referred command

;;; Device Status
;;  The following codes are used for reporting terminal/display settings, and vary depending on the implementation:

(defun escape (string)
  (substitute #\Escape #\Space string))

; (escape " a test string")
; "ateststring"


(defmacro def-vt100-command (name string args doc)
  `(defun ,name ,(append args '(&optional (stream *standard-input*)))
     ,doc
     (format stream ,(escape string) ,@args)))

Query Device Code	" [c" ()

    Requests a Report Device Code response from the device.

Report Device Code	" [~A0c" (code)

    Generated by the device in response to Query Device Code request.

Query Device Status	" [5n" ()

    Requests a Report Device Status response from the device.

Report Device OK	" [0n" ()

    Generated by the device in response to a Query Device Status request; indicates that device is functioning correctly.

Report Device Failure	" [3n" ()

    Generated by the device in response to a Query Device Status request; indicates that device is functioning improperly.

Query Cursor Position	" [6n" ()

    Requests a Report Cursor Position response from the device.

Report Cursor Position	" [~A;~AR" (ROW COLUMN)

    Generated by the device in response to a Query Cursor Position request; reports current cursor position.

Terminal Setup
The h and l codes are used for setting terminal/display mode, and vary depending on the implementation. Line Wrap is one of the few setup codes that tend to be used consistently:

Reset Device		" c" ()

    Reset all terminal settings to default.

Enable Line Wrap	" [7h" ()

    Text wraps to next line if longer than the length of the display area.

Disable Line Wrap	" [7l" ()

    Disables line wrapping.

Fonts
Some terminals support multiple fonts: normal/bold, swiss/italic, etc. There are a variety of special codes for certain terminals; the following are fairly standard:

Font Set G0		" " ()

    Set default font.

Font Set G1		" )" ()

    Set alternate font.

Cursor Control

Cursor Home 		" [~A;~AH" (ROW COLUMN)

    Sets the cursor position where subsequent text will begin. If no row/column parameters are provided (ie. " [H), the cursor will move to the home position, at the upper left of the screen." ()

Cursor Up		" [~AA" (COUNT)

    Moves the cursor up by COUNT rows; the default count is 1.

Cursor Down		" [~AB" (COUNT)

    Moves the cursor down by COUNT rows; the default count is 1.

Cursor Forward		" [~AC" (COUNT)

    Moves the cursor forward by COUNT columns; the default count is 1.

Cursor Backward		" [~AD" (COUNT)

    Moves the cursor backward by COUNT columns; the default count is 1.

Force Cursor Position	" [~A;~Af" (ROW COLUMN)

    Identical to Cursor Home.

Save Cursor		" [s" ()

    Save current cursor position.

Unsave Cursor		" [u" ()

    Restores cursor position after a Save Cursor.

Save Cursor & Attrs	" 7" ()

    Save current cursor position.

Restore Cursor & Attrs	" 8" ()

    Restores cursor position after a Save Cursor.

Scrolling

Scroll Screen		" [r" ()

    Enable scrolling for entire display.

Scroll Screen		" [~A;~Ar" (start end)

    Enable scrolling from row {start} to row {end}.

Scroll Down		" D" ()

    Scroll display down one line.

Scroll Up		" M" ()

    Scroll display up one line.

Tab Control

Set Tab 		" H" ()

    Sets a tab at the current position.

Clear Tab 		" [g" ()

    Clears tab at the current position.

Clear All Tabs 		" [3g" ()

    Clears all tabs.

Erasing Text

Erase End of Line	" [K" ()

    Erases from the current cursor position to the end of the current line.

Erase Start of Line	" [1K" ()

    Erases from the current cursor position to the start of the current line.

Erase Line		" [2K" ()

    Erases the entire current line.

Erase Down		" [J" ()

    Erases the screen from the current line down to the bottom of the screen.

Erase Up		" [1J" ()

    Erases the screen from the current line up to the top of the screen.

Erase Screen		" [2J" ()

    Erases the screen with the background colour and moves the cursor to home.

Printing
Some terminals support local printing:

Print Screen		" [i" ()

    Print the current screen.

Print Line		" [1i" ()

    Print the current line.

Stop Print Log		" [4i" ()

    Disable log.

Start Print Log		" [5i" ()

    Start log; all received text is echoed to a printer.

Define Key

Set Key Definition	" [~A;\"~A\"p" (key string)

    Associates a string of text to a keyboard key. {key} indicates the key by its ASCII value in decimal.

Set Display Attributes

Set Attribute Mode	" [{attr1};...;{attrn}m" ()

    Sets multiple display attribute settings. The following lists standard attributes:

    0	Reset all attributes
    1	Bright
    2	Dim
    4	Underscore	
    5	Blink
    7	Reverse
    8	Hidden

    	Foreground Colours
    30	Black
    31	Red
    32	Green
    33	Yellow
    34	Blue
    35	Magenta
    36	Cyan
    37	White

    	Background Colours
    40	Black
    41	Red
    42	Green
    43	Yellow
    44	Blue
    45	Magenta
    46	Cyan
    47	White

